import { RISGraph } from '../../domain/interfaces.js';

export interface MemoryArtifact {
  fileName: string;
  content: string;
}

export class MarkdownStore {
  /**
   * Deterministically serializes the RISGraph into the target artifacts.
   */
  serializeArtifacts(graph: RISGraph, artifactContents: Record<string, string>): MemoryArtifact[] {
    const artifacts: MemoryArtifact[] = [];
    
    // Override the raw contents with the actual generated markdown based on RISGraph claims
    const memoryBody = this.generateMemoryMd(graph);
    const architectBody = this.generateArchitectMd(graph);
    const guardrailsBody = this.generateGuardrailsMd(graph);

    artifacts.push({
      fileName: 'memory.md',
      content: this.formatWithFrontmatter(graph, memoryBody).replace(/\r\n/g, '\n')
    });
    artifacts.push({
      fileName: 'architect.md',
      content: this.formatWithFrontmatter(graph, architectBody).replace(/\r\n/g, '\n')
    });
    artifacts.push({
      fileName: 'guardrails.md',
      content: this.formatWithFrontmatter(graph, guardrailsBody).replace(/\r\n/g, '\n')
    });

    return artifacts;
  }

  private generateMemoryMd(graph: RISGraph): string {
    let md = `# ToMe Project Memory\n\n`;
    md += `> [!NOTE] Generated by ToMe v1.0.0. Manual edits to this file will be preserved as HUMAN_ASSERTED claims during the next \`tome update\`.\n\n`;
    
    md += `## Domains\n\n`;
    for (const d of graph.domains || []) {
      md += `### ${d.name?.value || 'Unknown'}\n`;
      if (d.description?.id) md += `<!-- TOME_CLAIM_ID: ${d.description.id} -->\n`;
      md += `${d.description?.value || ''}\n\n`;
    }

    md += `## Decisions\n\n`;
    for (const d of graph.decisions || []) {
      md += `### ${d.name?.value || 'Unknown'}\n`;
      if (d.description?.id) md += `<!-- TOME_CLAIM_ID: ${d.description.id} -->\n`;
      md += `${d.description?.value || ''}\n`;
      md += `- **Context:** ${d.context?.value || ''}\n`;
      md += `- **Status:** ${d.status?.value || ''}\n\n`;
    }

    md += `## Assumptions\n\n`;
    for (const a of graph.assumptions || []) {
      md += `### ${a.name?.value || 'Unknown'}\n`;
      if (a.description?.id) md += `<!-- TOME_CLAIM_ID: ${a.description.id} -->\n`;
      md += `${a.description?.value || ''}\n\n`;
    }

    md += `## Integrations\n\n`;
    for (const i of graph.integrations || []) {
      md += `### ${i.name?.value || 'Unknown'}\n`;
      if (i.description?.id) md += `<!-- TOME_CLAIM_ID: ${i.description.id} -->\n`;
      md += `${i.description?.value || ''}\n`;
      md += `- **Type:** ${i.type?.value || ''}\n`;
      md += `- **Protocol:** ${i.protocol?.value || ''}\n\n`;
    }

    return md;
  }

  private generateArchitectMd(graph: RISGraph): string {
    let md = `# ToMe Architecture State\n\n`;
    md += `> [!NOTE] Generated by ToMe v1.0.0.\n\n`;
    
    md += `## Services\n\n`;
    for (const s of graph.services || []) {
      md += `### ${s.name?.value || 'Unknown'}\n`;
      if (s.description?.id) md += `<!-- TOME_CLAIM_ID: ${s.description.id} -->\n`;
      md += `${s.description?.value || ''}\n\n`;
    }

    md += `## Capabilities\n\n`;
    for (const c of graph.capabilities || []) {
      md += `### ${c.name?.value || 'Unknown'}\n`;
      if (c.description?.id) md += `<!-- TOME_CLAIM_ID: ${c.description.id} -->\n`;
      md += `${c.description?.value || ''}\n\n`;
    }

    md += `## Workflows\n\n`;
    for (const w of graph.workflows || []) {
      md += `### ${w.name?.value || 'Unknown'}\n`;
      if (w.description?.id) md += `<!-- TOME_CLAIM_ID: ${w.description.id} -->\n`;
      md += `${w.description?.value || ''}\n`;
      md += `- **Trigger:** ${w.trigger?.value || 'Unknown'}\n`;
      md += `- **Steps:** ${(w.steps?.value || []).join(' -> ')}\n\n`;
    }

    md += `## Dependencies\n\n`;
    for (const d of graph.dependencies || []) {
      md += `### ${d.name || 'Unknown'}\n`;
      if (d.description?.id) md += `<!-- TOME_CLAIM_ID: ${d.description.id} -->\n`;
      md += `${d.description?.value || ''}\n\n`;
    }

    return md;
  }

  private generateGuardrailsMd(graph: RISGraph): string {
    let md = `# ToMe Guardrails\n\n`;
    md += `> [!IMPORTANT] These constraints must be respected by all developers and AI agents.\n\n`;
    
    md += `## Constraints\n\n`;
    for (const constraint of graph.constraints || []) {
      md += `### ${constraint.name?.value || 'Unknown'}\n`;
      if (constraint.description?.id) md += `<!-- TOME_CLAIM_ID: ${constraint.description.id} -->\n`;
      md += `${constraint.description?.value || ''}\n\n`;
    }

    md += `## Business Rules\n\n`;
    for (const b of graph.businessRules || []) {
      md += `### ${b.name?.value || 'Unknown'}\n`;
      if (b.description?.id) md += `<!-- TOME_CLAIM_ID: ${b.description.id} -->\n`;
      md += `${b.description?.value || ''}\n`;
      md += `- **Condition:** ${b.condition?.value || ''}\n`;
      md += `- **Enforcement:** ${b.enforcement?.value || ''}\n\n`;
    }

    return md;
  }

  private formatWithFrontmatter(graph: RISGraph, body: string): string {
    const yaml = [
      '---',
      `tome_version: "${graph.meta.tomeVersion}"`,
      `checksum: "${graph.meta.schemaVersion}"`, 
      `last_updated: "${graph.meta.lastUpdated}"`,
      '---',
      '',
      body
    ].join('\n');

    return yaml;
  }
}
